import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#050505" },
  container: { flex: 1, padding: 20 },

  // LAYAR AWAL (CLEAN)
  setupContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 60,
    justifyContent: "center",
  },
  headerCentered: { alignItems: "center", marginBottom: 20 },
  setupTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "900",
    marginTop: 15,
    letterSpacing: 1,
  },
  setupSubtitle: {
    color: "#888",
    fontSize: 14,
    textAlign: "center",
    marginTop: 8,
    width: "100%",
  },
  connectBtn: {
    backgroundColor: "#00ff88",
    paddingVertical: 18,
    width: "100%",
    borderRadius: 12,
    alignItems: "center",
  },
  connectBtnText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 1,
  },

  // DASHBOARD HEADER
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 30,
  },
  brandText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 2,
  },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  iconBtn: {
    padding: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#333",
    backgroundColor: "#111",
  },
  statusTag: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  statusText: { fontSize: 10, fontWeight: "bold", marginLeft: 6 },
  dot: { width: 6, height: 6, borderRadius: 3 },

  // MODAL SETTINGS
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBox: {
    backgroundColor: "#141414",
    width: "85%",
    padding: 25,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#333",
  },
  modalTitle: { color: "#fff", fontSize: 20, fontWeight: "bold" },

  tabBtn: { flex: 1, padding: 12, alignItems: "center", borderRadius: 8 },
  tabActive: { backgroundColor: "#00ff88" },
  tabText: { color: "#666", fontWeight: "bold" },

  configLabel: {
    color: "#888",
    fontSize: 10,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  configInput: {
    backgroundColor: "#000",
    color: "#00ff88",
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#222",
    fontSize: 14,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  scanBtnMini: {
    backgroundColor: "#00ff88",
    paddingHorizontal: 20,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },

  saveBtn: {
    backgroundColor: "#00ff88",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 10,
  },
  saveBtnText: { color: "#000", fontWeight: "bold", letterSpacing: 1 },

  // MODAL RADAR
  scannedItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0a0a0a",
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#222",
  },
  scannedItemName: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  scannedItemMac: { color: "#888", fontSize: 12, marginTop: 2 },

  // ... (SISA STYLE GAUGE TETAP SAMA)
  gaugeContainerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 35,
    gap: 10,
  },
  gaugeWrapper: { flex: 1, alignItems: "center" },
  mainRing: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 3,
    borderColor: "#111",
    backgroundColor: "#0a0a0a",
    justifyContent: "center",
    alignItems: "center",
    elevation: 15,
    shadowColor: "#00ff88",
    shadowRadius: 20,
    shadowOpacity: 0.15,
  },
  gaugeValueText: { color: "#fff", fontSize: 38, fontWeight: "900" },
  gaugeUnitText: {
    color: "#444",
    fontSize: 12,
    fontWeight: "bold",
    marginTop: -2,
    letterSpacing: 1,
  },
  rpmTrackSmall: {
    width: "70%",
    height: 3,
    backgroundColor: "#111",
    borderRadius: 2,
    marginTop: 10,
    overflow: "hidden",
  },
  rpmFillSmall: { height: "100%", backgroundColor: "#00ff88" },
  helperText: {
    color: "#333",
    fontSize: 10,
    fontWeight: "bold",
    marginTop: 10,
    letterSpacing: 2,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  card: {
    width: "31%",
    backgroundColor: "#0e0e0e",
    padding: 15,
    borderRadius: 15,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#151515",
  },
  cardValue: { color: "#fff", fontSize: 16, fontWeight: "bold", marginTop: 8 },
  cardLabel: {
    color: "#444",
    fontSize: 8,
    fontWeight: "bold",
    marginTop: 2,
    letterSpacing: 1,
  },
  trimContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 15,
    gap: 10,
  },
  trimBox: {
    flex: 1,
    backgroundColor: "#0e0e0e",
    padding: 15,
    borderRadius: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  trimLabel: { color: "#444", fontSize: 10, fontWeight: "bold" },
  trimValue: { color: "#00ff88", fontSize: 14, fontWeight: "bold" },
  fuelRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginTop: 10,
    backgroundColor: "#0e0e0e",
    padding: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#151515",
    marginBottom: 15,
  },
  fuelItem: { alignItems: "center" },
  fuelLabel: {
    color: "#444",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
  },
  fuelValue: { color: "#fff", fontSize: 20, fontWeight: "bold", marginTop: 5 },
  unitSmall: { fontSize: 10, color: "#666" },
  recordFabActive: {
    backgroundColor: "#1a1a1a", // Berubah gelap saat sedang merekam
    borderWidth: 2,
    borderColor: "#FF1744",
  },
  recordingDot: {
    position: "absolute",
    top: 15,
    right: 15,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
  },
  recordFabContainer: {
    position: "absolute",
    bottom: 90,
    right: 8,
    zIndex: 999,
  },
  recordFab: {
    width: 60, // Sedikit diperkecil agar lebih estetik
    height: 60,
    borderRadius: 30, // Harus persis setengah dari lebar/tinggi agar BULAT SEMPURNA
    backgroundColor: "#00ff88", // Merah Premium khas tombol Record
    justifyContent: "center",
    alignItems: "center",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 8,
  },
  secretZone: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 60, // Menutupi area Tab Bar Dashboard
    backgroundColor: "transparent",
  },
  hudLabel: {
    color: "rgba(255,255,255,0.3)",
    fontSize: 8,
    fontWeight: "bold",
    letterSpacing: 2,
    marginBottom: 2,
  },
  hudValueBig: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 26,
    fontWeight: "900",
  },
  hudValueSmall: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 16,
    fontWeight: "900",
  },
  hudUnit: {
    color: "rgba(255,255,255,0.35)",
    fontSize: 9,
    fontWeight: "bold",
    marginLeft: 4,
    letterSpacing: 1,
  },
});
