import { StyleSheet } from "react-native";

export const fuelStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  scrollContent: { padding: 15, paddingBottom: 100 },
  headerTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 3,
    marginBottom: 20,
    textAlign: "center",
  },

  heroCard: {
    backgroundColor: "#0e0e0e",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#1c1c1e",
  },
  heroLabel: {
    color: "#888",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2,
    marginBottom: 8,
  },
  heroValue: {
    color: "#00ff88",
    fontSize: 56,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  heroUnit: { color: "#666", fontSize: 16, fontWeight: "bold" },

  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  statCard: {
    width: "48%",
    backgroundColor: "#0e0e0e",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#1c1c1e",
  },
  statLabel: {
    color: "#888",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 6,
  },
  statValue: { color: "#fff", fontSize: 24, fontWeight: "900" },
  statUnit: { color: "#666", fontSize: 12, fontWeight: "bold" },

  priceCard: {
    backgroundColor: "#0e0e0e",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#1c1c1e",
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
  },
  priceLabel: { color: "#fff", fontSize: 13, fontWeight: "700" },
  priceInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#000",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#222",
    paddingHorizontal: 10,
  },
  priceCurrency: { color: "#666", fontSize: 13, fontWeight: "bold" },
  priceInput: {
    color: "#00ff88",
    fontSize: 15,
    fontWeight: "bold",
    paddingVertical: 10,
    paddingHorizontal: 6,
    minWidth: 90,
    textAlign: "right",
  },

  resetBtn: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
    backgroundColor: "rgba(255, 69, 58, 0.15)",
    borderRadius: 10,
    gap: 6,
    marginBottom: 24,
  },
  resetBtnText: { color: "#FF453A", fontSize: 12, fontWeight: "800" },

  sectionTitle: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 12,
  },

  historyCard: {
    backgroundColor: "#0e0e0e",
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#1c1c1e",
  },
  historyTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  historyDate: { color: "#888", fontSize: 11, fontWeight: "bold" },
  historyRoute: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    flex: 1,
    marginRight: 10,
  },
  historyStatsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  historyStatItem: { alignItems: "flex-start" },
  historyStatValue: { color: "#00ff88", fontSize: 14, fontWeight: "900" },
  historyStatLabel: {
    color: "#555",
    fontSize: 9,
    fontWeight: "bold",
    marginTop: 2,
  },

  emptyState: { alignItems: "center", paddingVertical: 40 },
  emptyStateText: {
    color: "#555",
    fontSize: 12,
    marginTop: 10,
    textAlign: "center",
  },
  calibrationCard: {
    backgroundColor: "#0e0e0e",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#1c1c1e",
  },
  calibrationValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginVertical: 14,
  },
  calibrationStepBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#222",
    alignItems: "center",
    justifyContent: "center",
  },
  calibrationValue: {
    color: "#00ff88",
    fontSize: 28,
    fontWeight: "900",
    minWidth: 80,
    textAlign: "center",
  },
  calibrationHint: {
    color: "#555",
    fontSize: 10,
    lineHeight: 16,
    marginTop: 4,
  },
  wizardBox: {
    backgroundColor: "#000",
    borderRadius: 12,
    padding: 14,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "#222",
  },
  wizardTitle: {
    color: "#ffcc00",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 8,
  },
  wizardStatRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  wizardStatValue: { color: "#fff", fontSize: 18, fontWeight: "900" },
  wizardStatLabel: {
    color: "#666",
    fontSize: 9,
    fontWeight: "bold",
    marginTop: 2,
  },
  wizardBtnRow: { flexDirection: "row", gap: 10 },
  wizardBtnPrimary: {
    flex: 1,
    backgroundColor: "#00ff88",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  wizardBtnPrimaryText: { color: "#000", fontWeight: "900", fontSize: 12 },
  wizardBtnCancel: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#444",
  },
  wizardBtnCancelText: { color: "#888", fontWeight: "bold", fontSize: 12 },
  wizardInputRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    alignItems: "center",
  },
});
