import { StyleSheet } from "react-native";
import { AppColors } from "../constants/appThemes";

export const getFuelStyles = (c: AppColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: c.bg, paddingHorizontal: 10 },
    scrollContent: { padding: 15, paddingBottom: 100 },
    headerTitle: {
      fontSize: 23,
      fontWeight: "900",
      color: c.text,
      letterSpacing: 3,
      marginBottom: 20,
      textAlign: "center",
    },

    heroCard: {
      backgroundColor: c.card,
      borderRadius: 20,
      padding: 24,
      alignItems: "center",
      marginBottom: 16,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    heroLabel: {
      color: c.textMuted,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 2,
      marginBottom: 8,
    },
    heroValue: {
      color: c.accent,
      fontSize: 56,
      fontWeight: "900",
      fontVariant: ["tabular-nums"],
    },
    heroUnit: { color: c.textMuted, fontSize: 16, fontWeight: "bold" },

    statsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      marginBottom: 16,
    },
    statCard: {
      width: "48%",
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    statLabel: {
      color: c.textMuted,
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1,
      marginBottom: 6,
    },
    statValue: { color: c.text, fontSize: 24, fontWeight: "900" },
    statUnit: { color: c.textMuted, fontSize: 12, fontWeight: "bold" },

    priceCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    priceRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 10,
    },
    priceLabel: { color: c.text, fontSize: 13, fontWeight: "700" },
    priceInputWrap: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.inputBg,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.border,
      paddingHorizontal: 10,
    },
    priceCurrency: { color: c.textMuted, fontSize: 13, fontWeight: "bold" },
    priceInput: {
      color: c.accent,
      fontSize: 15,
      fontWeight: "bold",
      paddingVertical: 10,
      paddingHorizontal: 6,
      minWidth: 90,
      textAlign: "right",
    },
    priceBtn: {
      backgroundColor: c.accent,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
    },
    priceBtnText: {
      color: c.bg,
      fontWeight: "900",
      fontSize: 12,
    },

    resetBtn: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 12,
      backgroundColor: "rgba(255, 69, 58, 0.15)",
      borderRadius: 10,
      gap: 6,
      marginBottom: 24,
    },
    resetBtnText: { color: "#FF453A", fontSize: 12, fontWeight: "800" },

    sectionTitle: {
      color: c.text,
      fontSize: 15,
      fontWeight: "800",
      letterSpacing: 1,
      marginBottom: 12,
    },

    historyCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      padding: 14,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    historyTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    historyDate: { color: c.textMuted, fontSize: 11, fontWeight: "bold" },
    historyRoute: {
      color: c.text,
      fontSize: 14,
      fontWeight: "700",
      flex: 1,
      marginRight: 10,
    },
    historyStatsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 4,
    },
    historyStatItem: { alignItems: "flex-start" },
    historyStatValue: { color: c.accent, fontSize: 14, fontWeight: "900" },
    historyStatLabel: {
      color: c.textFaint,
      fontSize: 9,
      fontWeight: "bold",
      marginTop: 2,
    },

    emptyState: { alignItems: "center", paddingVertical: 40 },
    emptyStateText: {
      color: c.textFaint,
      fontSize: 12,
      marginTop: 10,
      textAlign: "center",
    },

    calibrationCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    calibrationValueRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 16,
      marginVertical: 14,
    },
    calibrationStepBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: c.border,
      alignItems: "center",
      justifyContent: "center",
    },
    calibrationValue: {
      color: c.accent,
      fontSize: 28,
      fontWeight: "900",
      minWidth: 80,
      textAlign: "center",
    },
    calibrationHint: {
      color: c.textFaint,
      fontSize: 10,
      lineHeight: 16,
      marginTop: 4,
    },
    wizardBox: {
      backgroundColor: c.inputBg,
      borderRadius: 12,
      padding: 14,
      marginTop: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    wizardTitle: {
      color: "#ffcc00",
      fontSize: 12,
      fontWeight: "800",
      letterSpacing: 1,
      marginBottom: 8,
    },
    wizardStatRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    wizardStatValue: { color: c.text, fontSize: 18, fontWeight: "900" },
    wizardStatLabel: {
      color: c.textMuted,
      fontSize: 9,
      fontWeight: "bold",
      marginTop: 2,
    },
    wizardBtnRow: { flexDirection: "row", gap: 10 },
    wizardBtnPrimary: {
      flex: 1,
      backgroundColor: c.accent,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: "center",
    },
    wizardBtnPrimaryText: { color: c.bg, fontWeight: "900", fontSize: 12 },
    wizardBtnCancel: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.textFaint,
    },
    wizardBtnCancelText: {
      color: c.textMuted,
      fontWeight: "bold",
      fontSize: 12,
    },
    wizardInputRow: {
      flexDirection: "row",
      gap: 10,
      marginTop: 10,
      alignItems: "center",
    },
  });
