// styles/trip.styles.ts
import { StyleSheet } from "react-native";

export const tripStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000", padding: 15 },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 3,
  },
  syncBtn: {
    backgroundColor: "#1e1e1e",
    padding: 10,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: "#333",
  },

  summaryCard: {
    backgroundColor: "#1a1a1a",
    padding: 20,
    borderRadius: 15,
    marginBottom: 25,
    borderWidth: 1,
    borderColor: "#333",
  },
  summaryTitle: {
    color: "#888",
    fontSize: 12,
    fontWeight: "bold",
    letterSpacing: 1,
    marginBottom: 15,
    textAlign: "center",
  },
  summaryGrid: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  summaryItem: { alignItems: "center", flex: 1 },
  summaryDivider: { width: 1, height: 40, backgroundColor: "#333" },
  summaryValue: { fontSize: 24, fontWeight: "900", color: "#fff" },
  summaryUnit: { fontSize: 14, color: "#aaa", fontWeight: "normal" },
  summaryLabel: {
    fontSize: 10,
    color: "#888",
    marginTop: 5,
    fontWeight: "bold",
    letterSpacing: 1,
  },

  sectionTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 15,
    letterSpacing: 1,
    marginTop: 10,
  },
  tripCard: {
    backgroundColor: "#1e1e1e",
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
  },
  tripHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  tripDate: { color: "#888", fontSize: 12, fontWeight: "bold" },
  routeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    backgroundColor: "#252525",
    padding: 10,
    borderRadius: 8,
  },
  routeText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 10,
  },
  tripStatsGrid: { flexDirection: "row", justifyContent: "space-between" },
  tripStatBox: { flexDirection: "row", alignItems: "center" },
  tripStatText: {
    color: "#ccc",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 6,
  },

  modalContainer: { flex: 1, backgroundColor: "#121212" },
  modalContent: { padding: 20, flex: 1 },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: { fontSize: 24, fontWeight: "900", color: "#fff" },
  modalSubtitle: {
    fontSize: 14,
    color: "#00ffcc",
    marginTop: 4,
    fontWeight: "bold",
  },
  closeBtn: { backgroundColor: "#1e1e1e", padding: 8, borderRadius: 50 },
  mapContainer: {
    height: 250,
    borderRadius: 15,
    overflow: "hidden",
    marginBottom: 15,
    borderWidth: 2,
    borderColor: "#333",
  },
  map: { width: "100%", height: "100%" },

  playbackControls: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1a1a1a",
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#333",
  },
  playBtn: {
    width: 45,
    height: 45,
    borderRadius: 25,
    backgroundColor: "#00ffcc",
    justifyContent: "center",
    alignItems: "center",
  },

  telemetryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 15,
  },
  telemetryBox: {
    width: "48%",
    backgroundColor: "#1a1a1a",
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#333",
    alignItems: "center",
  },
  telemetryLabel: {
    color: "#888",
    fontSize: 10,
    fontWeight: "bold",
    letterSpacing: 1,
    marginBottom: 5,
  },
  telemetryValue: { color: "#fff", fontSize: 20, fontWeight: "900" },
  telemetryUnit: { color: "#aaa", fontSize: 12, fontWeight: "normal" },

  detailBox: {
    width: "48%",
    backgroundColor: "#1e1e1e",
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
  },
  detailLabel: {
    color: "#888",
    fontSize: 10,
    fontWeight: "bold",
    letterSpacing: 1,
    marginBottom: 5,
  },
  detailValue: { color: "#fff", fontSize: 16, fontWeight: "bold" },

  shareModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  shareModalContainer: {
    width: "90%",
    backgroundColor: "#1a1a1a",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#333",
  },
  shareModalTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
  },
  themeToggleContainer: {
    flexDirection: "row",
    backgroundColor: "#111",
    borderRadius: 10,
    padding: 4,
    marginBottom: 20,
    width: "100%",
  },
  themeBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 8,
  },
  themeBtnActive: { backgroundColor: "#00ffcc" },
  themeBtnText: { color: "#888", fontWeight: "bold", fontSize: 12 },
  captureArea: {
    width: 310, // Wajib sama persis dengan .card HTML (310px)
    height: 460, // Perkiraan tinggi total kartu agar tidak terpotong bawahnya
    backgroundColor: "transparent",
    overflow: "hidden",
    borderRadius: 16, // Harus sama dengan .card HTML agar rounded corner capture-nya pas
  },
  shareWebView: {
    width: 310, // Samakan lebar WebView dengan content kartu
    height: 460, // Samakan tinggi WebView dengan captureArea
    backgroundColor: "transparent",
  },
  shareActionRow: {
    flexDirection: "row",
    marginTop: 20,
    gap: 12,
    width: "100%",
  },
  shareCancelBtn: {
    flex: 1,
    backgroundColor: "#333",
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  shareCancelText: { color: "#fff", fontWeight: "bold" },
  shareSubmitBtn: {
    flex: 2,
    backgroundColor: "#00ffcc",
    flexDirection: "row",
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  shareSubmitText: { color: "#111", fontWeight: "900", fontSize: 16 },
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
  },
  emptyStateTitle: {
    color: "#888",
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 15,
    letterSpacing: 1,
  },
  emptyStateDesc: {
    color: "#555",
    fontSize: 12,
    marginTop: 5,
  },
  ecoBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  ecoText: { fontSize: 10, fontWeight: "bold" },
  playbackContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1e1e1e",
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#333",
  },
  sliderWrapper: { flex: 1 },
  timeLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 5,
    marginTop: -5,
  },
  timeText: { color: "#666", fontSize: 10, fontWeight: "bold" },
  timeTextCurrent: { color: "#00ffcc", fontSize: 12, fontWeight: "bold" },
  inspectorCard: {
    backgroundColor: "#1a1a1a",
    padding: 15,
    borderRadius: 12,
    marginBottom: 25,
    borderWidth: 1,
    borderColor: "#555",
  },
  inspectorHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
    paddingBottom: 10,
  },
  inspectorTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 8,
    flex: 1,
    letterSpacing: 1,
  },
  inspectorNote: {
    color: "#ffcc00",
    fontSize: 12,
    fontStyle: "italic",
    fontWeight: "bold",
  },

  inspectorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  inspectorBox: { width: "23%", alignItems: "center", marginBottom: 15 }, // margin bawah agar baris 1 & 2 berjarak
  gridDivider: {
    width: "100%",
    height: 1,
    backgroundColor: "#333",
    marginBottom: 15,
    marginTop: -5,
  }, // Pemisah antar baris
  inspectorLabel: {
    fontSize: 10,
    color: "#888",
    fontWeight: "bold",
    marginBottom: 4,
  },
  inspectorValue: { fontSize: 16, fontWeight: "900", color: "#fff" }, // Ukuran font disesuaikan agar 4 kolom muat
  inspectorUnit: { fontSize: 10, fontWeight: "normal" },
  detailGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 20,
  },
});
