import { StyleSheet } from "react-native";
import { AppColors } from "../constants/appThemes";

export const getTripStyles = (c: AppColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: c.bg, padding: 15 },
    headerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 10,
    },
    headerTitle: {
      fontSize: 26,
      fontWeight: "900",
      color: c.text,
      letterSpacing: 3,
    },
    syncBtn: {
      backgroundColor: c.card,
      padding: 10,
      borderRadius: 50,
      borderWidth: 1,
      borderColor: c.border,
    },

    summaryCard: {
      backgroundColor: c.card,
      padding: 20,
      borderRadius: 15,
      marginBottom: 25,
      borderWidth: 1,
      borderColor: c.border,
    },
    summaryTitle: {
      color: c.textMuted,
      fontSize: 12,
      fontWeight: "bold",
      letterSpacing: 1,
      marginBottom: 15,
      textAlign: "center",
    },
    summaryGrid: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    summaryItem: { alignItems: "center", flex: 1 },
    summaryDivider: { width: 1, height: 40, backgroundColor: c.border },
    summaryValue: { fontSize: 24, fontWeight: "900", color: c.text },
    summaryUnit: { fontSize: 14, color: c.textMuted, fontWeight: "normal" },
    summaryLabel: {
      fontSize: 10,
      color: c.textMuted,
      marginTop: 5,
      fontWeight: "bold",
      letterSpacing: 1,
    },

    sectionTitle: {
      color: c.text,
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 15,
      letterSpacing: 1,
    },
    tripCard: { backgroundColor: c.card, padding: 15, borderRadius: 12 },
    tripHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    tripDate: { color: c.textMuted, fontSize: 12, fontWeight: "bold" },
    routeContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 15,
      backgroundColor: c.inputBg,
      padding: 10,
      borderRadius: 8,
    },
    routeText: {
      color: c.text,
      fontSize: 16,
      fontWeight: "bold",
      marginLeft: 10,
    },
    tripStatsGrid: { flexDirection: "row", justifyContent: "space-between" },
    tripStatBox: { flexDirection: "row", alignItems: "center" },
    tripStatText: {
      color: c.textMuted,
      fontSize: 14,
      fontWeight: "bold",
      marginLeft: 6,
    },

    modalContainer: { flex: 1, backgroundColor: c.bg },
    modalContent: { padding: 20, flex: 1 },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    modalTitle: { fontSize: 24, fontWeight: "900", color: c.text },
    modalSubtitle: {
      fontSize: 14,
      color: c.accent,
      marginTop: 4,
      fontWeight: "bold",
    },
    closeBtn: { backgroundColor: c.card, padding: 8, borderRadius: 50 },
    mapContainer: {
      height: 250,
      borderRadius: 15,
      overflow: "hidden",
      marginBottom: 15,
      borderWidth: 2,
      borderColor: c.border,
    },
    map: { width: "100%", height: "100%" },

    playbackControls: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.card,
      padding: 15,
      borderRadius: 12,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: c.border,
    },
    playBtn: {
      width: 45,
      height: 45,
      borderRadius: 25,
      backgroundColor: c.accent,
      justifyContent: "center",
      alignItems: "center",
    },

    telemetryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      gap: 10,
      marginBottom: 15,
    },
    telemetryBox: {
      width: "48%",
      backgroundColor: c.card,
      padding: 15,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
    },
    telemetryLabel: {
      color: c.textMuted,
      fontSize: 10,
      fontWeight: "bold",
      letterSpacing: 1,
      marginBottom: 5,
    },
    telemetryValue: { color: c.text, fontSize: 20, fontWeight: "900" },
    telemetryUnit: { color: c.textMuted, fontSize: 12, fontWeight: "normal" },

    detailBox: {
      width: "48%",
      backgroundColor: c.card,
      padding: 15,
      borderRadius: 12,
      marginBottom: 10,
    },
    detailLabel: {
      color: c.textMuted,
      fontSize: 10,
      fontWeight: "bold",
      letterSpacing: 1,
      marginBottom: 5,
    },
    detailValue: { color: c.text, fontSize: 16, fontWeight: "bold" },

    shareModalOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      justifyContent: "center",
      alignItems: "center",
    },
    shareModalContainer: {
      width: "90%",
      backgroundColor: c.card,
      borderRadius: 20,
      padding: 20,
      alignItems: "center",
      borderWidth: 1,
      borderColor: c.border,
    },
    shareModalTitle: {
      color: c.text,
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 15,
    },
    themeToggleContainer: {
      flexDirection: "row",
      backgroundColor: c.inputBg,
      borderRadius: 10,
      padding: 4,
      marginBottom: 20,
      width: "100%",
    },
    themeBtn: {
      flex: 1,
      paddingVertical: 10,
      alignItems: "center",
      borderRadius: 8,
    },
    themeBtnActive: { backgroundColor: c.accent },
    themeBtnText: { color: c.textMuted, fontWeight: "bold", fontSize: 12 },
    captureArea: {
      width: 310,
      height: 460,
      backgroundColor: "transparent",
      overflow: "hidden",
      borderRadius: 16,
    },
    shareWebView: { width: 310, height: 460, backgroundColor: "transparent" },
    shareActionRow: {
      flexDirection: "row",
      marginTop: 20,
      gap: 12,
      width: "100%",
    },
    shareCancelBtn: {
      flex: 1,
      backgroundColor: c.border,
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: "center",
    },
    shareCancelText: { color: c.text, fontWeight: "bold" },
    shareSubmitBtn: {
      flex: 2,
      backgroundColor: c.accent,
      flexDirection: "row",
      paddingVertical: 14,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    shareSubmitText: { color: "#111", fontWeight: "900", fontSize: 16 },
    emptyStateContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 40,
    },
    emptyStateTitle: {
      color: c.textMuted,
      fontSize: 16,
      fontWeight: "bold",
      marginTop: 15,
      letterSpacing: 1,
    },
    emptyStateDesc: { color: c.textFaint, fontSize: 12, marginTop: 5 },
    ecoBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
    ecoText: { fontSize: 10, fontWeight: "bold" },
    playbackContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.card,
      padding: 15,
      borderRadius: 12,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: c.border,
    },
    sliderWrapper: { flex: 1 },
    timeLabels: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 5,
      marginTop: -5,
    },
    timeText: { color: c.textFaint, fontSize: 10, fontWeight: "bold" },
    timeTextCurrent: { color: c.accent, fontSize: 12, fontWeight: "bold" },
    inspectorCard: {
      backgroundColor: c.card,
      padding: 15,
      borderRadius: 12,
      marginBottom: 25,
      borderWidth: 1,
      borderColor: c.border,
    },
    inspectorHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      paddingBottom: 10,
    },
    inspectorTitle: {
      color: c.text,
      fontSize: 14,
      fontWeight: "bold",
      marginLeft: 8,
      flex: 1,
      letterSpacing: 1,
    },
    inspectorNote: {
      color: "#ffcc00",
      fontSize: 12,
      fontStyle: "italic",
      fontWeight: "bold",
    },

    inspectorGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    inspectorBox: { width: "23%", alignItems: "center", marginBottom: 15 },
    gridDivider: {
      width: "100%",
      height: 1,
      backgroundColor: c.border,
      marginBottom: 15,
      marginTop: -5,
    },
    inspectorLabel: {
      fontSize: 10,
      color: c.textMuted,
      fontWeight: "bold",
      marginBottom: 4,
    },
    inspectorValue: { fontSize: 16, fontWeight: "900", color: c.text },
    inspectorUnit: { fontSize: 10, fontWeight: "normal" },
    detailGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      marginBottom: 20,
    },
  });
